 version: '3.8'
 
 services:
   mixer:
     build:
       context: .
       dockerfile: services/mixer/Dockerfile
     container_name: mixer
     ports:
       - "5000:5000"
     env_file:
       - .env
     networks:
       - rng_network
     restart: unless-stopped
   
   generator:
     build:
       context: .
       dockerfile: services/generator/Dockerfile
     container_name: generator
     ports:
       - "5001:5001"
     env_file:
       - .env
     networks:
       - rng_network
       - herege-network
     depends_on:
       - mixer
     restart: unless-stopped
 
   # Exemplo 1: Um harvester para fontes rápidas (latência e rádio)
   harvester_fast:
     build:
       context: .
       dockerfile: services/harvester/Dockerfile # Você precisará criar este Dockerfile
     container_name: harvester_fast
     env_file:
       - .env
     environment:
       - HARVESTER_SOURCES=latency,radio
     devices:
       - "/dev/snd:/dev/snd"
     networks:
       - rng_network
     depends_on:
       - mixer
     restart: unless-stopped

   # Exemplo 2: Um harvester para fontes mais lentas (APIs externas)
   harvester_slow:
     build:
       context: .
       dockerfile: services/harvester/Dockerfile # Reutiliza o mesmo Dockerfile
     container_name: harvester_slow
     env_file:
       - .env
     environment:
       - HARVESTER_SOURCES=blockchain,currency,weather
     networks:
       - rng_network
     depends_on:
       - mixer
     restart: unless-stopped
 
 networks:
   rng_network:
     driver: bridge
   herege-network:
     external: true
