FROM python:3.11-slim

WORKDIR /app

# Instala ferramentas de compilação e as bibliotecas de áudio
RUN apt-get update && apt-get install -y build-essential python3-dev libportaudio2 portaudio19-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.radio.txt .

RUN pip install --no-cache-dir -r requirements.radio.txt

COPY . .

CMD ["python", "harvester_radio.py"]